### ISSUE TITLE
On favoriting the page shoots up to the top..

### ISSUE THREAD

**Issue by noudadrichem** [noudadrichem/keycapsets.com#50]
When I like a set the page shoots up to the top. This is very annoying and should be fixed.

**Comment by onebree** [comment]
Originally posted on the wrong issue last week:

-----

@noudadrichem I am still learning the codebase, but I believe the cause of this bug is how `<Link />` is used. I am not familiar with next, so will need to do trial-and-error debugging. But it _seems_ like the `children` of the component all collectively have an `onClick` handler, where clicking directs you to the provided URL. (This makes sense as to why the entire card is clickable.)

But by favoriting, you're shooting off multiple click handlers. First, on the direct target (the heart icon) that favorites the item. Next, an event bubbled up from the parent `<Link />` (or, image card element) to redirect the page. But this is stopped, and instead the current page is reloaded. (At least, this is what it seems like.)

Checking this out first, before any a11y improvements, since this is a main-feature bug

**Comment by noudadrichem** [comment]
This is also fixed wint `window.scrollTo`. I think it has something to do with render..
